wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714363629.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 4355
Eps_end:
  desc: null
  value: 0.1463147173336706
Eps_start:
  desc: null
  value: 0.48040395658215246
Lr:
  desc: null
  value: 0.0933899742091003
fc_layer:
  desc: null
  value: 11
mem_size:
  desc: null
  value: 5815
save_interval:
  desc: null
  value: 1709
timesteps:
  desc: null
  value: 48725
