wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714329615.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 9912
Eps_end:
  desc: null
  value: 0.3732431975373632
Eps_start:
  desc: null
  value: 0.7192653199285373
Lr:
  desc: null
  value: 0.09623120219938916
fc_layer_1:
  desc: null
  value: 79
fc_layer_2:
  desc: null
  value: 124
fc_layer_3:
  desc: null
  value: 45
mem_size:
  desc: null
  value: 49106
save_interval:
  desc: null
  value: 672
timesteps:
  desc: null
  value: 89567
