wandb_version: 1

Eps_start:
  desc: null
  value: 0.99
Eps_end:
  desc: null
  value: 0.05
Eps_decay:
  desc: null
  value: 5000
episodes:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712774224.0
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.16.6
      8:
      - 5
      13: darwin-arm64
