wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714337827.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 6393
Eps_end:
  desc: null
  value: 0.09611520426790104
Eps_start:
  desc: null
  value: 0.7135635133973217
Lr:
  desc: null
  value: 0.07175414313592161
fc_layer_1:
  desc: null
  value: 32
fc_layer_2:
  desc: null
  value: 39
fc_layer_3:
  desc: null
  value: 103
mem_size:
  desc: null
  value: 36527
save_interval:
  desc: null
  value: 1450
timesteps:
  desc: null
  value: 93793
