wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714386892.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 9749
Eps_end:
  desc: null
  value: 0.2827466353280647
Eps_start:
  desc: null
  value: 0.5878131361136113
Lr:
  desc: null
  value: 0.05893782091984723
fc_layer:
  desc: null
  value: 82
mem_size:
  desc: null
  value: 25717
save_interval:
  desc: null
  value: 713
timesteps:
  desc: null
  value: 1546
