[build-system]
requires = ["setuptools>=61.0.0", "wheel", "pybind11>=2.10.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SoccerAI"
version = "0.1.0"
description = "A Multi-Agent Reinforcement Learning framework for soccer environments."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.2.0",
    "numpy>=1.26.0",
    "wandb>=0.16.0",
    "tqdm>=4.66.0",
    "gymnasium>=0.29.0",
    "matplotlib>=3.5.0",
    "pybind11>=2.10.0"
]