wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714374323.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 17920
Eps_end:
  desc: null
  value: 0.06706314948221195
Eps_start:
  desc: null
  value: 0.28997734126532937
Lr:
  desc: null
  value: 0.028652480854934183
fc_layer:
  desc: null
  value: 104
mem_size:
  desc: null
  value: 4547
save_interval:
  desc: null
  value: 1647
timesteps:
  desc: null
  value: 52223
