wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714390556.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 19217
Eps_end:
  desc: null
  value: 0.40420840247371337
Eps_start:
  desc: null
  value: 0.7865357738044941
Lr:
  desc: null
  value: 0.03471749352415165
fc_layer:
  desc: null
  value: 79
mem_size:
  desc: null
  value: 31435
save_interval:
  desc: null
  value: 973
timesteps:
  desc: null
  value: 25313
