wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713512385.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 17068
Eps_end:
  desc: null
  value: 0.3101585259860586
Eps_start:
  desc: null
  value: 0.941183942072406
Lr:
  desc: null
  value: 0.033675966715215756
episodes:
  desc: null
  value: 3164
fc_layer_1:
  desc: null
  value: 57
fc_layer_2:
  desc: null
  value: 62
fc_layer_3:
  desc: null
  value: 90
mem_size:
  desc: null
  value: 30851
