wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714331520.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 19000
Eps_end:
  desc: null
  value: 0.056325854873131694
Eps_start:
  desc: null
  value: 0.9650339637397292
Lr:
  desc: null
  value: 0.014438561504976046
fc_layer_1:
  desc: null
  value: 39
fc_layer_2:
  desc: null
  value: 74
fc_layer_3:
  desc: null
  value: 73
mem_size:
  desc: null
  value: 11080
save_interval:
  desc: null
  value: 113
timesteps:
  desc: null
  value: 79014
