wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714341488.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 9163
Eps_end:
  desc: null
  value: 0.2900341487385394
Eps_start:
  desc: null
  value: 0.6929899647953941
Lr:
  desc: null
  value: 0.044727740863738506
fc_layer_1:
  desc: null
  value: 99
fc_layer_2:
  desc: null
  value: 109
fc_layer_3:
  desc: null
  value: 92
mem_size:
  desc: null
  value: 44911
save_interval:
  desc: null
  value: 1026
timesteps:
  desc: null
  value: 57273
