wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714389041.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 11852
Eps_end:
  desc: null
  value: 0.13713871553179816
Eps_start:
  desc: null
  value: 0.4393602777612794
Lr:
  desc: null
  value: 0.009656481471236312
fc_layer:
  desc: null
  value: 84
mem_size:
  desc: null
  value: 3148
save_interval:
  desc: null
  value: 1901
timesteps:
  desc: null
  value: 89121
