wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714332539.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 16860
Eps_end:
  desc: null
  value: 0.37712806991122666
Eps_start:
  desc: null
  value: 0.46028432395313607
Lr:
  desc: null
  value: 0.09923491649500964
fc_layer_1:
  desc: null
  value: 60
fc_layer_2:
  desc: null
  value: 57
fc_layer_3:
  desc: null
  value: 51
mem_size:
  desc: null
  value: 10472
save_interval:
  desc: null
  value: 971
timesteps:
  desc: null
  value: 34535
