wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714351413.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 15703
Eps_end:
  desc: null
  value: 0.3083918521540069
Eps_start:
  desc: null
  value: 0.5839737274411967
Lr:
  desc: null
  value: 0.004934995809674022
fc_layer_1:
  desc: null
  value: 23
fc_layer_2:
  desc: null
  value: 12
fc_layer_3:
  desc: null
  value: 31
mem_size:
  desc: null
  value: 13165
save_interval:
  desc: null
  value: 1008
timesteps:
  desc: null
  value: 16337
