wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714393657.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 13588
Eps_end:
  desc: null
  value: 0.4927337299545825
Eps_start:
  desc: null
  value: 0.3662875287996029
Lr:
  desc: null
  value: 0.07326903462382549
fc_layer:
  desc: null
  value: 86
mem_size:
  desc: null
  value: 10701
save_interval:
  desc: null
  value: 1236
timesteps:
  desc: null
  value: 48728
