wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714337781.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 16098
Eps_end:
  desc: null
  value: 0.06603516041259912
Eps_start:
  desc: null
  value: 0.7513811373850116
Lr:
  desc: null
  value: 0.03154978321790117
fc_layer_1:
  desc: null
  value: 18
fc_layer_2:
  desc: null
  value: 118
fc_layer_3:
  desc: null
  value: 81
mem_size:
  desc: null
  value: 15843
save_interval:
  desc: null
  value: 623
timesteps:
  desc: null
  value: 4126
