wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713516827.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 15221
Eps_end:
  desc: null
  value: 0.06470092893899548
Eps_start:
  desc: null
  value: 0.5620170083733822
Lr:
  desc: null
  value: 0.02870823803532808
episodes:
  desc: null
  value: 2862
fc_layer_1:
  desc: null
  value: 109
fc_layer_2:
  desc: null
  value: 109
fc_layer_3:
  desc: null
  value: 118
mem_size:
  desc: null
  value: 19421
