wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713499225.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 2403
Eps_end:
  desc: null
  value: 0.31052375690782225
Eps_start:
  desc: null
  value: 0.28526849687628086
Lr:
  desc: null
  value: 0.06305395278814703
episodes:
  desc: null
  value: 2989
fc_layer_1:
  desc: null
  value: 74
fc_layer_2:
  desc: null
  value: 30
fc_layer_3:
  desc: null
  value: 98
mem_size:
  desc: null
  value: 4478
