wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714392439.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 8749
Eps_end:
  desc: null
  value: 0.2377899452744293
Eps_start:
  desc: null
  value: 0.5989608664575443
Lr:
  desc: null
  value: 0.022990457817990872
fc_layer:
  desc: null
  value: 9
mem_size:
  desc: null
  value: 7170
save_interval:
  desc: null
  value: 1454
timesteps:
  desc: null
  value: 37831
