wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714349349.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 8364
Eps_end:
  desc: null
  value: 0.15995994607494024
Eps_start:
  desc: null
  value: 0.5558712343463676
Lr:
  desc: null
  value: 0.09200172886086364
fc_layer_1:
  desc: null
  value: 8
fc_layer_2:
  desc: null
  value: 114
fc_layer_3:
  desc: null
  value: 126
mem_size:
  desc: null
  value: 16320
save_interval:
  desc: null
  value: 870
timesteps:
  desc: null
  value: 87602
