wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712979463.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 13912
Eps_end:
  desc: null
  value: 0.06247711266826536
Eps_start:
  desc: null
  value: 0.840635221037777
Lr:
  desc: null
  value: 0.07019642018044232
episodes:
  desc: null
  value: 3576
