wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713515123.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 16114
Eps_end:
  desc: null
  value: 0.37544151905558915
Eps_start:
  desc: null
  value: 0.6609028771870364
Lr:
  desc: null
  value: 0.013055468749525711
episodes:
  desc: null
  value: 2368
fc_layer_1:
  desc: null
  value: 83
fc_layer_2:
  desc: null
  value: 14
fc_layer_3:
  desc: null
  value: 123
mem_size:
  desc: null
  value: 34550
