wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712978824.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 19016
Eps_end:
  desc: null
  value: 0.4565692772167369
Eps_start:
  desc: null
  value: 0.9508985764197472
Lr:
  desc: null
  value: 0.0006771231454251581
episodes:
  desc: null
  value: 1684
