wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714329597.0
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.16.6
      8:
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 6491
Eps_end:
  desc: null
  value: 0.1849723696204497
Eps_start:
  desc: null
  value: 0.6394675339494138
Lr:
  desc: null
  value: 0.03614565815797282
fc_layer_1:
  desc: null
  value: 109
fc_layer_2:
  desc: null
  value: 18
fc_layer_3:
  desc: null
  value: 113
mem_size:
  desc: null
  value: 34999
save_interval:
  desc: null
  value: 703
timesteps:
  desc: null
  value: 43190
