wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714383376.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 5710
Eps_end:
  desc: null
  value: 0.20092603828275624
Eps_start:
  desc: null
  value: 0.8870214381112115
Lr:
  desc: null
  value: 0.02111195091876525
fc_layer:
  desc: null
  value: 38
mem_size:
  desc: null
  value: 37808
save_interval:
  desc: null
  value: 1321
timesteps:
  desc: null
  value: 53298
