wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713527524.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
Eps_decay:
  desc: null
  value: 5770
Eps_end:
  desc: null
  value: 0.032959876664381486
Eps_start:
  desc: null
  value: 0.8497784330439744
Lr:
  desc: null
  value: 0.026023414335508397
episodes:
  desc: null
  value: 2891
fc_layer_1:
  desc: null
  value: 10
fc_layer_2:
  desc: null
  value: 66
fc_layer_3:
  desc: null
  value: 22
mem_size:
  desc: null
  value: 35414
